root: true
env:
  es6: true
  node: true
  browser: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - next/core-web-vitals
  - prettier
plugins:
  - '@typescript-eslint'
  - unused-imports
parser: '@typescript-eslint/parser'
rules:
  no-unused-vars: off
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars:
    - warn
    - vars: all
      varsIgnorePattern: '^_'
      args: after-used
      argsIgnorePattern: '^_'
