import { Box, Grid } from "@mui/material";
import { Inter } from "next/font/google";
import HeaderBar from "@/components/HeaderBar";
import Profile from "@/components/Profile";
import "./global.scss";
import TagList from "@/components/TagList";

const inter = Inter({ subsets: ["latin"] });

// TODO: metadata考える
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Box sx={{ width: { xs: "90%", md: "70%" }, m: "auto" }}>
          <HeaderBar />
          <Box sx={{ mt: 5 }}>
            <Grid
              container
              spacing={5}
              flexWrap="wrap"
              justifyContent="space-around"
              alignContent="flex-start"
            >
              <Grid item lg={7}>
                {children}
              </Grid>
              <Grid item lg={3}>
                <Profile />
                <TagList />
              </Grid>
            </Grid>
          </Box>
        </Box>
      </body>
    </html>
  );
}
